### PR TITLE
add affiliations

### PR DESCRIPTION
**Pull request by Smit-create**

### CODE REVIEW

**Comment by shlff** [comment]
Thanks @jstac @Smit-create and the team. 

I'd love to be added and please find my name and affiliation here:

Shu Hu 
The Australian National University

**Comment by cc7768** [comment]
Hey all! This is great - You can put my affiliation as New York University.

**Comment by jstac** [comment]
From Quentin Batista: 

I would be happy to be a co-author. My current affiliation is MIT.

**Comment by Smit-create** [comment]
I think this is good to merge now. We have everyone's affiliation. Thank you all!

**Comment by albop** [comment]
Sorry I've been late there. @jstac and @Smit-create  Is it still possible to add me and my two affiliations ? 
- ESCP Business School and Ecole Polytechnique

**Comment by jstac** [comment]
No problem @albop , I'll take care of it.

**Pull request merged**
