### PR TITLE
Setup CI and sample paper

### PR DESCRIPTION
**Pull request by Smit-create**
cc @jstac @mmcky 

#2

### CODE REVIEW

**Comment by Smit-create** [comment]
This PR works fine on my fork: https://github.com/Smit-create/qe_libraries_article/pull/1. The CI doesn't run on this PR maybe because I don't have the write access to the repo.

**Comment by mmcky** [comment]
@Smit-create I have updated your permissions to the repo

**Comment by Smit-create** [comment]
Let's merge and check if this works.

**Comment by Smit-create** [comment]
The CI is working and the results can be seen at https://github.com/QuantEcon/qe_libraries_article/actions/runs/3683249525. The pdf version of the generated paper is found in the artifacts section.

**Pull request merged**
